name: SunnyCoinflip
version: '1.3'
main: org.ItsInspector.sunnyCoinflip.SunnyCoinflip
api-version: '1.21'
depend: [Vault]
softdepend: [PlaceholderAPI]

commands:
  coinflip:
    description: Comando principale per il coinflip
    aliases: [cf]
    usage: /cf <classici|pillars|bedfight|bw|bf|info>
  setpillarsfirst:
    description: Imposta la posizione del primo pillar
    permission: sunnycoinflip.admin
  setpillarsopponent:
    description: Imposta la posizione dello sfidante dei pillars
    permission: sunnycoinflip.admin
  pillars:
    description: Comando per scommettere sui pillars

permissions:
  sunnycoinflip.admin:
    description: Gestione amministrativa di SunnyCoinflip
    default: op
libraries:
  - net.bytebuddy:byte-buddy:1.14.12
  - net.bytebuddy:byte-buddy-agent:1.14.12
